# Generated by Django 5.0.7 on 2024-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
